version: '2'

services:
  master:
    build: ./hadoop-master
    ports:
      - "9870:9870"
      - "8088:8088"
      - "19888:19888"
      - "8188:8188"
    container_name: "master"

  worker1:
    build: ./hadoop-worker
    container_name: "worker1"
    ports:
      - "9901:9864"
      - "8041:8042"

