version: '3'

services:
  master:
    image: minchen57/hadoop-docker-python-sentiment-compose-master:latest
    ports:
      - "8088:8088"
      - "19888:19888"
      - "8188:8188"
      - "50070:50070"
      - "50075:50075"
      - "50010:50010"
    container_name: "master"
    hostname: "master"
    domainname: "master"
    entrypoint: ["/etc/bootstrap.sh", "-run"]

  worker:
    image: minchen57/hadoop-docker-python-sentiment-compose-worker:latest
    #container_name: "worker1"
    depends_on:
      - master
    deploy:
      mode: replicated
      replicas: 1






