# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.vm_tags import VMTags  # noqa: F401,E501
from swagger_server import util


class VM(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id=None, creation_timestamp=None, name=None, description=None, tags=None, machine_type=None, status=None, status_message=None, zone=None, can_ip_forward=None):  # noqa: E501
        """VM - a model defined in Swagger

        :param id: The id of this VM.  # noqa: E501
        :type id: str
        :param creation_timestamp: The creation_timestamp of this VM.  # noqa: E501
        :type creation_timestamp: datetime
        :param name: The name of this VM.  # noqa: E501
        :type name: str
        :param description: The description of this VM.  # noqa: E501
        :type description: str
        :param tags: The tags of this VM.  # noqa: E501
        :type tags: VMTags
        :param machine_type: The machine_type of this VM.  # noqa: E501
        :type machine_type: str
        :param status: The status of this VM.  # noqa: E501
        :type status: str
        :param status_message: The status_message of this VM.  # noqa: E501
        :type status_message: str
        :param zone: The zone of this VM.  # noqa: E501
        :type zone: str
        :param can_ip_forward: The can_ip_forward of this VM.  # noqa: E501
        :type can_ip_forward: bool
        """
        self.swagger_types = {
            'id': str,
            'creation_timestamp': datetime,
            'name': str,
            'description': str,
            'tags': VMTags,
            'machine_type': str,
            'status': str,
            'status_message': str,
            'zone': str,
            'can_ip_forward': bool
        }

        self.attribute_map = {
            'id': 'id',
            'creation_timestamp': 'creationTimestamp',
            'name': 'name',
            'description': 'description',
            'tags': 'tags',
            'machine_type': 'machineType',
            'status': 'status',
            'status_message': 'statusMessage',
            'zone': 'zone',
            'can_ip_forward': 'canIpForward'
        }

        self._id = id
        self._creation_timestamp = creation_timestamp
        self._name = name
        self._description = description
        self._tags = tags
        self._machine_type = machine_type
        self._status = status
        self._status_message = status_message
        self._zone = zone
        self._can_ip_forward = can_ip_forward

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VM of this VM.  # noqa: E501
        :rtype: VM
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this VM.


        :return: The id of this VM.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this VM.


        :param id: The id of this VM.
        :type id: str
        """

        self._id = id

    @property
    def creation_timestamp(self):
        """Gets the creation_timestamp of this VM.


        :return: The creation_timestamp of this VM.
        :rtype: datetime
        """
        return self._creation_timestamp

    @creation_timestamp.setter
    def creation_timestamp(self, creation_timestamp):
        """Sets the creation_timestamp of this VM.


        :param creation_timestamp: The creation_timestamp of this VM.
        :type creation_timestamp: datetime
        """

        self._creation_timestamp = creation_timestamp

    @property
    def name(self):
        """Gets the name of this VM.


        :return: The name of this VM.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this VM.


        :param name: The name of this VM.
        :type name: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this VM.


        :return: The description of this VM.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this VM.


        :param description: The description of this VM.
        :type description: str
        """

        self._description = description

    @property
    def tags(self):
        """Gets the tags of this VM.


        :return: The tags of this VM.
        :rtype: VMTags
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this VM.


        :param tags: The tags of this VM.
        :type tags: VMTags
        """

        self._tags = tags

    @property
    def machine_type(self):
        """Gets the machine_type of this VM.


        :return: The machine_type of this VM.
        :rtype: str
        """
        return self._machine_type

    @machine_type.setter
    def machine_type(self, machine_type):
        """Sets the machine_type of this VM.


        :param machine_type: The machine_type of this VM.
        :type machine_type: str
        """

        self._machine_type = machine_type

    @property
    def status(self):
        """Gets the status of this VM.


        :return: The status of this VM.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this VM.


        :param status: The status of this VM.
        :type status: str
        """
        allowed_values = ["PROVISIONING", "STAGING", "RUNNING", "STOPPING", "STOPPED", "SUSPENDING", "SUSPENDED", "TERMINATED"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def status_message(self):
        """Gets the status_message of this VM.


        :return: The status_message of this VM.
        :rtype: str
        """
        return self._status_message

    @status_message.setter
    def status_message(self, status_message):
        """Sets the status_message of this VM.


        :param status_message: The status_message of this VM.
        :type status_message: str
        """

        self._status_message = status_message

    @property
    def zone(self):
        """Gets the zone of this VM.


        :return: The zone of this VM.
        :rtype: str
        """
        return self._zone

    @zone.setter
    def zone(self, zone):
        """Sets the zone of this VM.


        :param zone: The zone of this VM.
        :type zone: str
        """

        self._zone = zone

    @property
    def can_ip_forward(self):
        """Gets the can_ip_forward of this VM.


        :return: The can_ip_forward of this VM.
        :rtype: bool
        """
        return self._can_ip_forward

    @can_ip_forward.setter
    def can_ip_forward(self, can_ip_forward):
        """Sets the can_ip_forward of this VM.


        :param can_ip_forward: The can_ip_forward of this VM.
        :type can_ip_forward: bool
        """

        self._can_ip_forward = can_ip_forward
